apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Run Selenium Tests via CB workflow

on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  test:
    # runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: cloudbees-io/checkout@v1

    - name: Set up Java
      uses: docker://registry-1.docker.io/library/openjdk:11-jdk
      # with:
      #   java-version: '11'
      #   distribution: 'temurin'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run tests with Maven
      run: mvn test
